name: Sync Tencent Docs

on:
  workflow_dispatch:
  # TODO GitHub 的 CI 机器访问不到腾讯文档的链接，暂时无法使用。
  # schedule:
  #   # 北京时间 每天 23:29（为了避免延迟，打一点提前量）。
  #   - cron: "29 15 * * *"

jobs:
  sync:
    name: Sync Tencent Docs

    runs-on: [self-hosted]

    container:
      image: node:22-bookworm

    env:
      TENCENT_ACCESS_TOKEN: ${{ secrets.TENCENT_ACCESS_TOKEN }}
      TENCENT_CLIENT_ID: ${{ secrets.TENCENT_CLIENT_ID }}
      TENCENT_OPEN_ID: ${{ secrets.TENCENT_OPEN_ID }}

    steps:
      # 拉取仓库代码。
      - name: Check Out Git Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      # 安装 Python。
      - name: Install Python
        run: |
          apt update
          apt install -y python3 python3-pip python3-venv

          python -V

      # 安装项目依赖。
      - name: Install Dependencies
        run: npm install

      # # 执行同步脚本。
      # - name: Run Sync Script
      #   run: npm run sync-tencent-doc

      # # 生成最新数据文件。
      # - name: Generate Newest Data
      #   run: npm run generate-data

      # # 生成提交日期（北京时间）。
      # - name: Generate Commit Time
      #   run: |
      #     export TZ='Asia/Shanghai'
      #     echo "COMMIT_TIME=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      # # 提交变更。
      # - name: Commit Changes
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     add: "."
      #     message: "Auto Sync Tencent Docs (${{ env.COMMIT_TIME }})"
      #     default_author: github_actions
