name: Unit Test

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags:
      - "v*"

jobs:
  unit-test:
    name: Run Unit Test
    runs-on: windows-latest

    steps:
      # 检出 Git 仓库。
      - name: Check Out Git Repository
        uses: actions/checkout@v4

      # 安装 pnpm。
      - name: Setup Pnpm
        uses: pnpm/action-setup@v4

      # 安装 Node.js。
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      # 安装项目依赖。
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      # 执行单元测试。
      - name: Run Unit Test
        run: pnpm run test
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
